# Generated by Django 4.2.7 on 2023-11-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=200, null=True)),
                ('Publisher', models.CharField(max_length=200, null=True)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
