# Generated by Django 4.2.7 on 2023-11-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='English',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='Genra',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='Hindi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='Marathi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
