# Generated by Django 4.2.7 on 2023-11-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_book_english_remove_book_hindi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
