# Generated by Django 4.2.7 on 2023-11-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart',
            new_name='website',
        ),
    ]
