# Generated by Django 4.2.7 on 2023-12-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delivered_order_id_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivered',
            name='book_order',
        ),
    ]
