# Generated by Django 4.2.7 on 2023-12-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_delivered_book_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivered',
            name='book_order',
        ),
    ]
