# Generated by Django 4.2.7 on 2023-12-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_delivered_book_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivered',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='delivered',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
