# Generated by Django 4.2.7 on 2023-12-29 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_delivered_date_ord_alter_delivered_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivered',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.address'),
        ),
    ]
