# Generated by Django 4.2.7 on 2023-12-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_delivered_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivered',
            name='Cur_add',
            field=models.CharField(max_length=900, null=True),
        ),
    ]
